<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <TargetFramework>net7.0-windows</TargetFramework>
    <AssemblyName>Flow.Launcher.Plugin.Desmos</AssemblyName>
    <PackageId>Flow.Launcher.Plugin.Desmos</PackageId>
    <Authors>coweggs</Authors>
    <PackageProjectUrl>https://github.com/coweggs/Flow.Launcher.Plugin.Desmos</PackageProjectUrl>
    <RepositoryUrl>https://github.com/coweggs/Flow.Launcher.Plugin.Desmos</RepositoryUrl>
    <PackageTags>flow-launcher flow-plugin</PackageTags>
    <CopyLocalLockFileAssemblies>true</CopyLocalLockFileAssemblies>
    <AppendTargetFrameworkToOutputPath>false</AppendTargetFrameworkToOutputPath>
  </PropertyGroup>

  <PropertyGroup Condition="'$(Configuration)|$(Platform)'=='Release|AnyCPU'">
    <DebugSymbols>false</DebugSymbols>
    <DebugType>None</DebugType>
  </PropertyGroup>

  <ItemGroup>
    <Content Include="plugin.json">
      <CopyToOutputDirectory>Always</CopyToOutputDirectory>
    </Content>
    <Content Include="desmos.png">
      <CopyToOutputDirectory>Always</CopyToOutputDirectory>
    </Content>
  </ItemGroup>

  <ItemGroup>
    <PackageReference Include="Flow.Launcher.Plugin" Version="4.4.0" />
    <PackageReference Include="Microsoft.Web.WebView2" Version="*" />
  </ItemGroup>

</Project>
